// src/strings.js
export const strings = {
  es: {
    start: 'Iniciar asistente',
    nameQuestion: '¿Cómo te llamas?',
    email: 'Correo electrónico',
    countryQuestion: '¿En qué país te encuentras?',
    regionQuestion: '¿En qué provincia/estado/territorio?',
    hectaresQuestion: '¿Cuántas hectáreas tienes?',
    cropQuestion: '¿Qué cultivo estás asesorando?',
    phaseQuestion: '¿En qué fase se encuentra?',
    productionType: 'Tipo de producción',
    selectProductionType: 'Selecciona el tipo de producción',
    conventional: 'Convencional',
    organic: 'Ecológica',
    acceptStorage: 'Acepto el almacenamiento de mis datos para mejorar el servicio.',
    seePolicy: 'Ver política de privacidad',
    viewRecommendations: 'Ver recomendaciones',
    next: 'Siguiente',
    thankYou: 'Gracias por confiar en nosotros',
    productsRecommended: 'Productos recomendados para',
    noProducts: 'No se encontraron productos recomendados.',
    errorEmail: 'Correo inválido',
    errorName: 'Nombre inválido',
    errorHectares: 'Introduce un número válido de hectáreas',
    emailSuccess: 'Correo enviado correctamente',
    emailError: 'Error al enviar el correo',
    phaseNames: {
      FLOR: 'Floración', ENR: 'Enraizamiento', CUA: 'Cuajado', ENG: 'Engorde',
      MAD: 'Maduración', SN: 'Sanidad', VEG: 'Vegetativo', BRO: 'Brotación',
      PR: 'Prefloración', NAS: 'Nascencia', AHI: 'Ahijado', ENC: 'Encañado',
      RAD: 'Dosis radicular'
    },
  },
  en: {
    start: 'Start Assistant',
    nameQuestion: 'What is your name?',
    email: 'Email',
    countryQuestion: 'Which country are you in?',
    regionQuestion: 'Which province/state/region?',
    hectaresQuestion: 'How many hectares do you have?',
    cropQuestion: 'What crop are you advising?',
    phaseQuestion: 'What stage is it in?',
    productionType: 'Type of production',
    selectProductionType: 'Select production type',
    conventional: 'Conventional',
    organic: 'Organic',
    acceptStorage: 'I accept the storage of my data to improve the service.',
    seePolicy: 'View privacy policy',
    viewRecommendations: 'See recommendations',
    next: 'Next',
    thankYou: 'Thank you for trusting us',
    productsRecommended: 'Recommended products for',
    noProducts: 'No recommended products found.',
    errorEmail: 'Invalid email',
    errorName: 'Invalid name',
    errorHectares: 'Enter a valid number of hectares',
    emailSuccess: 'Email sent successfully',
    emailError: 'Error sending email',
    phaseNames: {
      FLOR: 'Flowering', ENR: 'Rooting', CUA: 'Fruit set', ENG: 'Fattening',
      MAD: 'Ripening', SN: 'Health', VEG: 'Vegetative', BRO: 'Sprouting',
      PR: 'Pre-flowering', NAS: 'Emergence', AHI: 'Tiller', ENC: 'Stem elongation',
      RAD: 'Root dosage'
    },
  }
};
