export const strings = {
  es: {
    start: 'Iniciar asistente',
    slogan: 'Juntos cambiamos\nel mundo',

    nameQuestion: '¿Cómo te llamas?',
    email: 'Correo electrónico',
    countryQuestion: '¿En qué país te encuentras?',
    regionQuestion: '¿En qué provincia/estado/territorio?',
    hectaresQuestion: '¿Cuántas hectáreas tienes?',
    cropQuestion: '¿Qué cultivo estás asesorando?',
    phaseQuestion: '¿En qué fase se encuentra?',
    productionType: 'Tipo de producción',
    selectProductionType: 'Selecciona el tipo de producción',
    conventional: 'Convencional',
    organic: 'Ecológica',
    acceptStorage: 'Acepto el almacenamiento de mis datos para mejorar el servicio.',
    seePolicy: 'Ver política de privacidad',
    viewRecommendations: 'Ver recomendaciones',
    next: 'Siguiente',
    thankYou: 'Gracias por confiar en nosotros',
    productsRecommended: 'Productos recomendados para',
    noProducts: 'No se encontraron productos recomendados.',
    errorEmail: 'Correo inválido',
    errorName: 'Nombre inválido',
    errorHectares: 'Introduce un número válido de hectáreas',
    emailSuccess: 'Correo enviado correctamente',
    emailError: 'Error al enviar el correo',
    reviewData: 'Revisar Datos',
    confirmAndSend: 'Confirmar y Enviar',
    edit: 'Editar',
    startOver: 'Empezar de nuevo',
    noRecommendations: 'No se han encontrado productos recomendados.',
    share: 'Compartir',
    seeGlossary: '¿Qué significa esto?',

    phaseNames: {
      FLOR: 'Floración',
      ENR: 'Enraizamiento',
      CUA: 'Cuajado',
      ENG: 'Engorde',
      MAD: 'Maduración',
      SN: 'Sanidad',
      VEG: 'Vegetativo',
      BRO: 'Brotación',
      PR: 'Prefloración',
      NAS: 'Nascencia',
      AHI: 'Ahijado',
      ENC: 'Encañado',
      RAD: 'Dosis radicular'
    },
    glossaryPhaseNames: {
      vegetativo: 'Vegetativo',
     enraizamiento: 'Enraizamiento',
      floracion: 'Floración',
      cuajado: 'Cuajado',
      engorde: 'Engorde',
      maduracion: 'Maduración',
    },
    crops: {
      tomate: 'Tomate',
      pimiento: 'Pimiento',
      berenjena: 'Berenjena',
      calabacin: 'Calabacín',
      pepino: 'Pepino',
      sandia: 'Sandía',
      melon: 'Melón',
      olivo: 'Olivo',
      viña: 'Viña',
      almendro: 'Almendro',
      pistacho: 'Pistacho',
      cereal: 'Cereal',
      lechuga: 'Lechuga',
      col: 'Col',
      brocoli: 'Brócoli',
      coliflor: 'Coliflor',
      ciruelo: 'Ciruelo',
      melocoton: 'Melocotón',
      cerezo: 'Cerezo',
      albaricoque: 'Albaricoque',
      manzana: 'Manzana',
      pera: 'Pera',
      naranja: 'Naranja',
      mandarina: 'Mandarina',
      limon: 'Limón',
      zanahoria: 'Zanahoria',
      patata: 'Patata',
      ajo: 'Ajo',
      cebolla: 'Cebolla',
      fresa: 'Fresa',
      frambuesa: 'Frambuesa',
      arandano: 'Arándano',
      mora: 'Mora',
    }
  },

  en: {
    start: 'Start Assistant',
    slogan: 'Together we change\nthe world',

    nameQuestion: 'What is your name?',
    email: 'Email',
    countryQuestion: 'Which country are you in?',
    regionQuestion: 'Which province/state/region?',
    hectaresQuestion: 'How many hectares do you have?',
    cropQuestion: 'What crop are you advising?',
    phaseQuestion: 'What stage is it in?',
    productionType: 'Type of production',
    selectProductionType: 'Select production type',
    conventional: 'Conventional',
    organic: 'Organic',
    acceptStorage: 'I accept the storage of my data to improve the service.',
    seePolicy: 'View privacy policy',
    viewRecommendations: 'See recommendations',
    next: 'Next',
    thankYou: 'Thank you for trusting us',
    productsRecommended: 'Recommended products for',
    noProducts: 'No recommended products found.',
    errorEmail: 'Invalid email',
    errorName: 'Invalid name',
    errorHectares: 'Enter a valid number of hectares',
    emailSuccess: 'Email sent successfully',
    emailError: 'Error sending email',
     reviewData: 'Review Data',
    confirmAndSend: 'Confirm and Send',
    edit: 'Edit',
    startOver: 'Start Over',
    noRecommendations: 'No recommended products found.',
    share: 'Share',
    seeGlossary: 'What does this mean?',

    phaseNames: {
      FLOR: 'Flowering',
      ENR: 'Rooting',
      CUA: 'Fruit set',
      ENG: 'Fattening',
      MAD: 'Ripening',
      SN: 'Health',
      VEG: 'Vegetative',
      BRO: 'Sprouting',
      PR: 'Pre-flowering',
      NAS: 'Emergence',
      AHI: 'Tiller',
      ENC: 'Stem elongation',
      RAD: 'Root dosage'
    },
      glossaryPhaseNames: {
      vegetativo: 'Vegetative',
      enraizamiento: 'Rooting',
      floracion: 'Flowering',
      cuajado: 'Setting',
      engorde: 'Enlarging',
      maduracion: 'Maturing',
   },
    crops: {
      tomate: 'Tomato',
      pimiento: 'Pepper',
      berenjena: 'Eggplant',
      calabacin: 'Zucchini',
      pepino: 'Cucumber',
      sandia: 'Watermelon',
      melon: 'Melon',
      olivo: 'Olive',
      viña: 'Vineyard',
      almendro: 'Almond',
      pistacho: 'Pistachio',
      cereal: 'Cereal',
      lechuga: 'Lettuce',
      col: 'Cabbage',
      brocoli: 'Broccoli',
      coliflor: 'Cauliflower',
      ciruelo: 'Plum',
      melocoton: 'Peach',
      cerezo: 'Cherry',
      albaricoque: 'Apricot',
      manzana: 'Apple',
      pera: 'Pear',
      naranja: 'Orange',
      mandarina: 'Mandarin',
      limon: 'Lemon',
      zanahoria: 'Carrot',
      patata: 'Potato',
      ajo: 'Garlic',
      cebolla: 'Onion',
      fresa: 'Strawberry',
      frambuesa: 'Raspberry',
      arandano: 'Blueberry',
      mora: 'Blackberry',
    }
  }
};
